### ISSUE TITLE
Planned Features

### ISSUE THREAD

**Issue by dulleh** [dulleh/akhyou#1]
- *Integration with Hummingbird and MAL* - would be in the sidebar.   
- *Chromecast support* - Not sure how this will work, I could add another button along with "Download" and "Stream" but that might look cluttered. Better idea might be to make download and Chromecast icons on the left and restore "cancel" to it's material guidelines' position.
Also, I don't have a Chromecast... so that might be a problem.  
- *More anime providers*  - _AnimeBam.net_ **DONE**, MasterAni.me, KissAnime (THIS ONE WON'T HAPPEN SOON), chia-anime.tv, rawranime.tv, animeonhand.com.
- _*A way to notify the user of updates* - preferably a simple call to a server that returns the link to the latest version apk. I don't have a server though (nor the money to run one). Was thinking about Parse?_ **DONE** 
- *Enhanced browsing* - was thinking of letting the user input hashtags in search and returning the appropriate anime listings in response. Seems like a big task.

**Comment by wopian** [comment]
>Chromecast support - Not sure how this will work, I could add another button along with "Download" and "Stream" but that might look cluttered. Better idea might be to make download and Chromecast icons on the left and restore "cancel" to it's material guidelines' position. Also, I don't have a Chromecast... so that might be a problem.

Can test this function if ever required.

**Comment by Syborg49** [comment]
Hyped for no 1 enhancement.

**Comment by dulleh** [comment]
Moving these into separate issues.
