### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Triikay** [dulleh/akhyou#27]
I'm sorry to say this but after the update (2.0.2) Akhyou has been crashing for me, I can make it work only if I clear the data but every time I kill the app and opens it again it just keep crashing, and I dont want to spend my day clearing the data just to make it work. Would you please fix this. Thanks in advance.

**Comment by SpaceUI** [comment]
Same thing happened to me after updating. It's unusable right now. Hope it can get fixed. Keep up the great work with this app!

**Comment by dulleh** [comment]
So sorry about this. I didn't test the changes nearly enough! Will get it fixed ASAP

**Comment by dulleh** [comment]
@Triikay and @SpaceUI  [here's a, hopefully, fixed version](https://github.com/dulleh/akhyou/blob/master/akhyou-latest.apk?raw=true)

**Comment by dulleh** [comment]
Crashes still occurring.

**Comment by SpaceUI** [comment]
![screenshot_2016-02-16-09-14-38](https://cloud.githubusercontent.com/assets/17243765/13080333/dd41fca4-d48d-11e5-880c-f49e96774cc8.png)
Getting this error now, not fixed when closing and opening app.

**Comment by dulleh** [comment]
Oh sorry i should clarify that that is a KissAnime bug. It is supposed to fix itself after five seconds though (KissAnime has a 5 second loading screen).

**Comment by SpaceUI** [comment]
Doesn't work even after waiting 5 seconds. Shame. Kissanime often has good res episodes.

**Comment by dulleh** [comment]
Fixed as of 292c9ac825ec00cfeb8f4ee3680d010921169b21.
