### ISSUE TITLE
Favorites 

### ISSUE THREAD

**Issue by Triikay** [dulleh/akhyou#29]
So a bug showed, don't  if its just me. But I've been having issues adding anime to favorites, an error always pops up.

 https://app.box.com/s/i1gsky3svy5rx78kgky6npi1xj58uo8p

**Comment by dulleh** [comment]
Hi, did this only appear in the latest version or has it been happening previously? (You can check your version in settings, latest is 2.0.3.)

**Comment by Triikay** [comment]
In the latest version

**Comment by dulleh** [comment]
Duplicated of #21
