### ISSUE TITLE
Can't pull any episodes on school WiFi.. Can I get a link to the one before the big update?

### ISSUE THREAD

**Issue by MiniMoose12** [dulleh/akhyou#31]
I personally use this app to get anime for lunch time at school. Since the last update its been having weird issues like nothing showing for animeram and other sources. As well as failed to get URL errors. I was wondering of you had a backup of the version right before the crashing started?  Thanks. :3

**Comment by dulleh** [comment]
AnimeRam has updated their website. The fix and a new update will be up shortly.

For future reference, old versions can be found by going [here](https://github.com/dulleh/akhyou/commits/master/akhyou-latest.apk) > choose a version (you want 2.0.1 in this case) > `view` on `akhyou-latest.apk` > `view the full file`

**Comment by dulleh** [comment]
Let me know if it's fixed @MiniMoose12 and I'll close this issue.

**Comment by MiniMoose12** [comment]
Its very wishy washy... I just updated and its throwing errors on a few sources trying to grab videos..... Anime ram is throwing unexpected URLs... Was able to get me video from another source so that's great... Not sure how many will work at my school though but that's not your problem :3. Keep up the good work and I can see this app being excellent in a year or so. Probably the easiest way to grab videos on the go ATM.
