### ISSUE TITLE
Permissions on 6.0

### ISSUE THREAD

**Issue by yuukiw** [dulleh/akhyou#34]
Please request sd card premesion on Android 6.0

**Comment by Sarabveer** [comment]
It should be automatic, I'm on Marshmallow and it asked me for Data Permissions

**Comment by yuukiw** [comment]
Not my end. Instead of asking he just says no premisions to write.

**Comment by dulleh** [comment]
@yuukiw I assume this happens when you try and download an episode?

**Comment by Sarabveer** [comment]
Yea

**Comment by yuukiw** [comment]
yes.

I now gave it the premission via the app manager but it never asked for it after installed it again after i made an clean install of 6.0

**Comment by MiniMoose12** [comment]
I'm on android 6.0.1 and yep it never asked for permissions and refused to download a ep. Did what he mentioned above and gave it storage permissions through the app manager and I can download EPs fine now... :/

**Comment by dulleh** [comment]
Will be fixed by next release.

**Comment by dulleh** [comment]
Fixed as of 5d6623d403226b934123dcde03f38adc3a00b94c
