### ISSUE TITLE
SUGGESTION 

### ISSUE THREAD

**Issue by RyeCribbyTree** [dulleh/akhyou#35]
Can you please add Chrome Cast support? This is by far the best anime app for android but I can't easily stream it to my Chrome Cast.

**Comment by dulleh** [comment]
Hi @RyeCribbyTree, the [AllCast app](https://play.google.com/store/apps/details?id=com.koushikdutta.cast&hl=en_GB) works for casting (I use it myself :+1: ) so I recommend you use that.

**Comment by dulleh** [comment]
As an aside, the intent system in Android makes having a dedicated app for dedicated tasks possible - thereby minimizing bloat in apps as well as providing a, hopefully, better experience by having apps do what they do _well_. In theory, if all apps promoted this philosophy - as they should - the ecosystem (as well as individual apps) would be more sustainable and of higher quality.
