### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by laserstrike** [dulleh/akhyou#38]
Do you have any plans to get your app on F-Droid? It's like the play store, but for open source apps. 

https://f-droid.org/wiki/page/Inclusion_Policy

Tachiyomi is a manga app that's on there. It would be great if we had one for anime, too. 

Of course, it's up to you.

**Comment by j2ghz** [comment]
v2.0.4 and before violate this policy. @dulleh is working to remove fabric.io so it can be included.

**Comment by dulleh** [comment]
Yep, I'll get it up on fdroid once I'm done with finals.

**Comment by j2ghz** [comment]
Progress tracked at https://gitlab.com/fdroid/fdroiddata/merge_requests/1555

**Comment by spiral6** [comment]
Has there been any further progress in putting this on F-Droid?

**Comment by laserstrike** [comment]
It's already on F-Droid. I think you can close this issue.
