### ISSUE TITLE
Akhyou won't display anything

### ISSUE THREAD

**Issue by Syborg49** [dulleh/akhyou#43]
Displays error Everytime, link 
https://youtu.be/Xlo-lm7QXQ0

**Comment by dulleh** [comment]
Hey I had this exact issue myself a couple days ago too. It seems to have gone now for me, though. Is it still occurring on your end? 
I'll see if I can replicate and then fix it :+1:

**Comment by Syborg49** [comment]
Sorry, false alarm @dulleh. Seems fixed now
