### ISSUE TITLE
No sources and Can't play this video

### ISSUE THREAD

**Issue by Rem10033** [dulleh/akhyou#45]
When using kissanime as a source some anime's like azumanga daioh and Mayoiga says there isn't a source (been going on for two days) and occasionally when using other sources it says "Can't play this video"

**Comment by dulleh** [comment]
Yep, KissAnime is definitely broken right now. Will try to fix today but if I can't get it done now unfortunately I don't think I'll have time for a while.

**Comment by Rem10033** [comment]
Thanks for the help just saw the update :)

**Comment by dulleh** [comment]
My pleasure ^^

**Comment by Rem10033** [comment]
Actually there is another bug when launching the app it says Unfortunately Akhyou! Has stopped
