### ISSUE TITLE
Unfortunately Akhyou! Has stopped

### ISSUE THREAD

**Issue by Rem10033** [dulleh/akhyou#46]
Since the new update came when launching the app I get the message "Unfortunately, Akhyou! has stopped"

**Comment by WesleyBlack** [comment]
I had the same problem you have to uninstall and then reinstall the app

**Comment by WesleyBlack** [comment]
unfortunately you'll lose your list so before doing so I'd recommend taking some screenshots or make a list on a notepad or something

**Comment by Rem10033** [comment]
I'm still getting the same error

**Comment by WesleyBlack** [comment]
what device are you using? and what android version is it running?

**Comment by Rem10033** [comment]
Moto G 3rd Gen and Android 6.0.1

**Comment by WesleyBlack** [comment]
so you tried deleting the app and downloaded a new copy from this github and installed it right

**Comment by Rem10033** [comment]
Yeah I uninstalled it and reinstalled it many times

**Comment by WesleyBlack** [comment]
and it still wouldn't open

**Comment by Rem10033** [comment]
Yeah

**Comment by WesleyBlack** [comment]
idk what to say, sorry I couldn't be of more help the only other thing I can think of to try would be to restart  your device

**Comment by Rem10033** [comment]
Oh it worked thanks :)

**Comment by WesleyBlack** [comment]
no problem glad to see it worked

**Comment by dulleh** [comment]
Sorry about this! Don't know what exactly is causing it but I've heard that clearing app data, uninstalling and now rebooting all work to fix it.

**Comment by chriskevini** [comment]
I've updated the app not knowing about this issue. Is there a way to save my favorites before I clear app data and reinstall the app?

**Comment by dulleh** [comment]
No, unfortunately there isn't. I'm really sorry.

**Comment by chriskevini** [comment]
Which file is the data stored in? I'd like to give it a look if I can. It would really sadden me if everything has to be deleted. Thanks for your help!

**Comment by dulleh** [comment]
Hi, I don't actually have a rooted device at hand so can't check but the
easiest way to backup/restore would probably be to use something like
Helium on the play store. Let me know if it works (but I expect that it
will not because what's causing the crashes is probably a compatibility
issue with previous saved data).

**Comment by chriskevini** [comment]
Unfortunately it didn't work. Rip my faves. Oh well. Great work on the app anyways. It's my go-to anime app. Hoping to one day get those hummingbird features. Keep up the good work!

**Comment by dulleh** [comment]
Yeah, thanks. I'll test for this stuff more thoroughly in future >.<
