### ISSUE TITLE
Set Download Location

### ISSUE THREAD

**Issue by malakigerald19** [dulleh/akhyou#47]
Wish we can set the Download path of the downloaded anime. Some of us have limited internal storage but have a larger external storage. Also, when pressing back button the app doesn't go to the main page instead it exits the app O.o

Bless you for Making this app. I will donate if I have to :dancers:

**Comment by dulleh** [comment]
lol no donation needed. Put money towards the anime producers themselves if you can!

Downloads are still so sucky in the app right now. I suppose creating a little dialog box for each download in which you can set the file name and the path is the best option.

The back button only returns to search within that session. So if you swipe away the app from recents it won't return you to search when hitting back the next time you open the app. Is it not returning to search ever?

**Comment by malakigerald19** [comment]
The Download feature is working great  for me 😎😎 my only problem is when downloading from kissanime the filename is so long and don't have a file extension that's why mx player can't see it.


The back button works just ad you said I swipe away the app and open ot thats why I can't go to search again.

**Comment by dulleh** [comment]
Fixed as of c3100bdbe6b8526b20976612d417fbe199ba72f1
