### ISSUE TITLE
Episode Tracking Broken

### ISSUE THREAD

**Issue by chriskevini** [dulleh/akhyou#49]
Since updating, the red highlight on watched episodes no longer appears.

**Comment by dulleh** [comment]
Hi, it seems to be working to me. Can you give details on when this occurs?

**Comment by WesleyBlack** [comment]
I'd suggest you try manually updating one of the episodes by clicking and holding on an episode and then watch a episode you didn't before and see if that's works if not try force stopping the app in device setting and if you still face the problem restart your device

**Comment by chriskevini** [comment]
I was on an old version. The issue does not exist on the newest version.
