### ISSUE TITLE
Instant crash when opening v2.0.5

### ISSUE THREAD

**Issue by Blazeflack** [dulleh/akhyou#52]
The latest version is not working at all for me. It fails to open and just consistently crashes instead. 

Is there a log somewhere with info you need?

I'm running CyanogenMod 13 on a OnePlus One with Danish system language.

**Comment by WesleyBlack** [comment]
check out #46.

**Comment by Blazeflack** [comment]
Unfortunately that did not work for me. I tried booting into recovery and wipe dalvik and cache too.

**Comment by Blazeflack** [comment]
I stand corrected. I must have forgot to uninstall  before rebooting last time. I just tried again and it seems to work fine this time.

Thank you.
