### ISSUE TITLE
Search Issue in Kissanime

### ISSUE THREAD

**Issue by CycX** [dulleh/akhyou#54]
Search function not working in kissanime?
I like the video quality in kissanime, hope you fix it. Thank you for your awesome app :)

**Comment by dulleh** [comment]
Yes, it's broken. Was trying to fix yesterday and today (see 8df4c39ccbf54859f41ba5a0193c8786df9bd493) but no luck so far.

**Comment by hthuong09** [comment]
Just a reminder, AFAK, KissAnime doesn't always work. Because sometimes, KissAnime (or you can say cloudflare) shows "Recaptcha" screen instead of "Loading. Please wait 5 seconds" sreen and that recaptcha _can't be_ automated bypassed. That has something to do with the IP so I don't think we could wait and try again.

@dulleh: I think you should alert the user when and recaptcha appears let them know to try other providers instead.

**Comment by dulleh** [comment]
Oh yeah, I forgot about that but I'm not sure that's what's causing it to fail here because it's consistently not working. I haven't seen that screen in my testing, I'll try and look for it today.

**Comment by verseses** [comment]
Is it because of this? https://www.reddit.com/r/KissAnime/comments/4srrnd/uanime_app/

**Comment by dulleh** [comment]
Update on this: Cloudflare is working fine for AnimeRush but still no luck with KissAnime.

**Comment by hthuong09** [comment]
How about find a replacement for kissanime? htvanime.com is exactly a clone of kissanime, using google as a video provider.

**Comment by haramdaddy** [comment]
@hthuong09 why would you want to find a replacement for kissanime? it does its job really well. this is only a temporary hiccup imo. in the mean time, you can just go to kissanime website and stream it from there.

**Comment by hthuong09** [comment]
I meant just for this app. Because kissanime is not stable in this app and htvanime is a clone of kissanime (they use kissanime's videos) without cloudflare protection.

**Comment by dulleh** [comment]
I don't think we should just give up on KissAnime support completely. I do like the idea of having a backup for when KissAnime is down, however, so I'll see if I can't build a htvanime parser today and send out an update.

**Comment by dulleh** [comment]
@hthuong09 none of the videos are loading for me on htvanime so i guess that's a no go :smile:
