### ISSUE TITLE
Kissanime issue

### ISSUE THREAD

**Issue by jetgoop** [dulleh/akhyou#61]
On Kissanime half the vids I try to open just say that it can't open the link. I always use Kissanime because it has the best quality. Is this a problem with the app or Kissanime itself? It'd also be great if you could add more servers with quality as good as Kissanime.

**Comment by dulleh** [comment]
If you could post specific anime/episodes on which this occurs I will be glad to look into it. It may also be a problem with your video player if the error message isn't displayed inside Akhyou itself.

**Comment by jetgoop** [comment]
Well I've been having this problem with several random episodes in Avatar the last airbender, the legend of korra, another, ergo proxy dub, koyomimonogatari, cowboy bebop, samurai champloo and others. I thought the problem was my player so I downloaded some others and it still wouldn't work. If you could look into it that'd be awesome. Thanks, man

**Comment by dulleh** [comment]
And do those episodes also randomly start working again?

**Comment by dulleh** [comment]
nice taste btw

**Comment by jetgoop** [comment]
They've never started working again for me

**Comment by jetgoop** [comment]
Thanks lol

**Comment by dulleh** [comment]
Can't say I can replicate the problem unfortunately

**Comment by dulleh** [comment]
If you could provide a specific anime and episode it's occuring on @jetgoop I can try to fix it. Otherwise I can't do much.

**Comment by jetgoop** [comment]
Wow, guess what? All the vids are working now. Thanks anyway man

**Comment by dulleh** [comment]
Ahaha, no problem, glad it's working. I wish I knew what caused these inconsistent errors >.<
