### ISSUE TITLE
Internal Player & Kissanime 

### ISSUE THREAD

**Issue by PixelNephilim** [dulleh/akhyou#62]
Just downloaded this app as a replacement for uAnime since it stopped working, and I have a suggestion that is quite annoying to go without. 

Instead of opening the browser and playing it there, please either  institute some sort of internal player, or create a setting that uses the device's internal player. Not having this is a big downside to me. 

Also, Kissanime videos aren't working because many of them were taken down. That's why they won't work. 

Besides that, I like the app so far. Great design and great idea.

**Comment by wopian** [comment]
Use [MX Player](https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.ad&hl=en_GB). Far better than any browser or internal player could ever hope to be.

**Comment by dulleh** [comment]
^

**Comment by dulleh** [comment]
I'll see if I can prevent the browser from showing up as an option.
