### ISSUE TITLE
Kissanime sourced anime giving me a white screen 

### ISSUE THREAD

**Issue by haramdaddy** [dulleh/akhyou#73]
Attached are images of the issue:
https://imgur.com/gallery/AMYf8

I have tried refreshing multiple times but nothing shows up. It was working only a couple of hours ago. I have also restarted my phone as well as reinstalled the app. 

It would be much appreciated if this is fixed.

**Comment by dulleh** [comment]
Yeah it was working for me last night. I think KissAnime must have updated something. I'll see about getting it fixed whenever I have time.

**Comment by NarenME001** [comment]
Http response is 503,
Cloudflare might be responsible for it.

**Comment by Atemu** [comment]
#72
